routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
if (isset($router)) {

    $router->get('auth', 'Auth\LoginController@login')->name('login');
    $router->post('auth', 'Auth\LoginController@login')->name('auth');
    $router->get('logout', 'Auth\LoginController@logout')->name('logout');

    $router->get('/', 'Site\HomeController@index')->name('front.index');
    $router->get('linha/{slug}', 'Site\HomeController@show_line')->name('linha.show');
    $router->get('contato', 'Site\ContactController@index')->name('contact.index');
    $router->post('contato', 'Site\ContactController@store')->name('contact.store');
    $router->get('a-empresa', 'Site\HomeController@about')->name('about.index');
    $router->get('video-institucional', 'Site\HomeController@video')->name('video.index');

    $router->group(['middleware' => 'auth', 'prefix' => 'admin'], function () use ($router) {
        $router->get('/', function () {
            return redirect()->route('line.index');
        });
        $router->get('/panel', function () {
            return redirect()->route('line.index');
        })->name('dashboard');

        $router->resource('user', 'Admin\UserController');

        //Multi Móveis
        $router->resource('line', 'Admin\LineController');
        $router->resource('lead', 'Admin\LeadController', [
            'except' => ['create', 'edit', 'destroy']
        ]);

        $router->resource('product', 'Admin\ProductController');
        $router->resource('blog', 'Admin\BlogController');

        $router->resource('environment', 'Admin\EnvironmentController');
    });

}

resources/views/admin/elements/menu.blade.php
<!-- Left navbar-header -->
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse slimscrollsidebar">
        <ul class="nav" id="side-menu">
            <li>
                <a href="{!! route('user.index') !!}" class="waves-effect">
                    <span class="hide-menu">Meu Perfil / Representantes</span>
                </a>
            </li>
            <li>
                <a href="{!! route('lead.index') !!}" class="waves-effect">
                    <span class="hide-menu">Contato</span>
                </a>
            </li>
            <li>
                <a href="{!! route('line.index') !!}" class="waves-effect">
                    <span class="hide-menu">Linhas</span>
                </a>
            </li>
            <li>
                <a href="{!! route('product.index') !!}" class="waves-effect">
                    <span class="hide-menu">Gerenciar Módulos</span>
                </a>
            </li>
            <li>
                <a href="{!! route('blog.index') !!}" class="waves-effect">
                    <span class="hide-menu">Novidades</span>
                </a>
            </li>
        </ul>
    </div>
</div>
<!-- Left navbar-header end -->

resources/views/admin/elements/notifications.blade.php
<li class="dropdown"> <a class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#"><i class="icon-envelope"></i>
        <div class="notify"><span class="heartbit"></span><span class="point"></span></div>
    </a>
    <ul class="dropdown-menu mailbox animated bounceInDown">
        <li>
            <div class="drop-title">You have 4 new messages</div>
        </li>
        <li>
            <div class="message-center">
                <a href="#">
                    <div class="user-img"> <img src="/images/users/pawandeep.jpg" alt="user" class="img-circle"> <span class="profile-status online pull-right"></span> </div>
                    <div class="mail-contnet">
                        <h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:30 AM</span> </div>
                </a>
                <a href="#">
                    <div class="user-img"> <img src="/images/users/sonu.jpg" alt="user" class="img-circle"> <span class="profile-status busy pull-right"></span> </div>
                    <div class="mail-contnet">
                        <h5>Sonu Nigam</h5> <span class="mail-desc">I've sung a song! See you at</span> <span class="time">9:10 AM</span> </div>
                </a>
                <a href="#">
                    <div class="user-img"> <img src="/images/users/arijit.jpg" alt="user" class="img-circle"> <span class="profile-status away pull-right"></span> </div>
                    <div class="mail-contnet">
                        <h5>Arijit Sinh</h5> <span class="mail-desc">I am a singer!</span> <span class="time">9:08 AM</span> </div>
                </a>
                <a href="#">
                    <div class="user-img"> <img src="/images/users/pawandeep.jpg" alt="user" class="img-circle"> <span class="profile-status offline pull-right"></span> </div>
                    <div class="mail-contnet">
                        <h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:02 AM</span> </div>
                </a>
            </div>
        </li>
        <li>
            <a class="text-center" href="javascript:void(0);"> <strong>See all notifications</strong> <i class="fa fa-angle-right"></i> </a>
        </li>
    </ul>
    <!-- /.dropdown-messages -->
</li>
<!-- /.dropdown -->

resources/views/admin/elements/pagination.blade.php
@if ($paginator->count() > 2)
    <ul class="pagination pagination-lg m-b-0">
        <li{{ ($paginator->currentPage() == 1) ? ' class=disabled' : '' }}>
            <a href="{{ ($paginator->currentPage() == 1) ? '#' : $paginator->url(1) }}">
                <i class="fa fa-angle-left"></i>
            </a>
        </li>

        @for ($i = 1; $i <= $paginator->lastPage(); $i++)
            <li{{ ($paginator->currentPage() == $i) ? ' class=active' : '' }}>
                <a href="{{ $paginator->url($i) }}">
                    {!! $i !!}
                </a>
            </li>
        @endfor

        <li{{ ($paginator->currentPage() == $paginator->lastPage()) ? ' class=disabled' : '' }}>
            <a href="{{ ($paginator->currentPage() == $paginator->lastPage()) ? '#' : $paginator->url($paginator->currentPage()+1) }}">
                <i class="fa fa-angle-right"></i>
            </a>
        </li>
    </ul>
@endif

resources/views/admin/elements/progress.blade.php
<li class="dropdown"> <a class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#"><i class="icon-note"></i>
        <div class="notify"><span class="heartbit"></span><span class="point"></span></div>
    </a>
    <ul class="dropdown-menu dropdown-tasks animated slideInUp">
        <li>
            <a href="#">
                <div>
                    <p> <strong>Task 1</strong> <span class="pull-right text-muted">40% Complete</span> </p>
                    <div class="progress progress-striped active">
                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%"> <span class="sr-only">40% Complete (success)</span> </div>
                    </div>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <p> <strong>Task 2</strong> <span class="pull-right text-muted">20% Complete</span> </p>
                    <div class="progress progress-striped active">
                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%"> <span class="sr-only">20% Complete</span> </div>
                    </div>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <p> <strong>Task 3</strong> <span class="pull-right text-muted">60% Complete</span> </p>
                    <div class="progress progress-striped active">
                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%"> <span class="sr-only">60% Complete (warning)</span> </div>
                    </div>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <p> <strong>Task 4</strong> <span class="pull-right text-muted">80% Complete</span> </p>
                    <div class="progress progress-striped active">
                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%"> <span class="sr-only">80% Complete (danger)</span> </div>
                    </div>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a class="text-center" href="#"> <strong>See All Tasks</strong> <i class="fa fa-angle-right"></i> </a>
        </li>
    </ul>
    <!-- /.dropdown-tasks -->
</li>
<!-- /.dropdown -->

resources/views/admin/elements/user.blade.php
<li>
    <a href="{!! route('logout') !!}">
        <i class="fa fa-power-off"></i>
        Sair
    </a>
</li>