routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
if (isset($router)) {

    $router->get('auth', 'Auth\LoginController@login')->name('login');
    $router->post('auth', 'Auth\LoginController@login')->name('auth');
    $router->get('logout', 'Auth\LoginController@logout')->name('logout');

    $router->get('/', 'Site\HomeController@index')->name('front.index');
    $router->get('linha/{slug}', 'Site\HomeController@show_line')->name('linha.show');
    $router->get('contato', 'Site\ContactController@index')->name('contact.index');
    $router->post('contato', 'Site\ContactController@store')->name('contact.store');
    $router->get('a-empresa', 'Site\HomeController@about')->name('about.index');
    $router->get('video-institucional', 'Site\HomeController@video')->name('video.index');

    $router->group(['middleware' => 'auth', 'prefix' => 'admin'], function () use ($router) {
        $router->get('/', function () {
            return redirect()->route('line.index');
        });
        $router->get('/panel', function () {
            return redirect()->route('line.index');
        })->name('dashboard');

        $router->resource('user', 'Admin\UserController');

        //Multi Móveis
        $router->resource('line', 'Admin\LineController');
        $router->resource('lead', 'Admin\LeadController', [
            'except' => ['create', 'edit', 'destroy']
        ]);

        $router->resource('product', 'Admin\ProductController');
        $router->resource('blog', 'Admin\BlogController');

        $router->resource('environment', 'Admin\EnvironmentController');
    });

}

app/Line.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Line extends Model
{

    use SoftDeletes;

    protected $fillable = [
        'name', 'slug', 'descriptions'
    ];

    public function getDescriptionsJsonAttribute()
    {
        return json_decode($this->descriptions, true);
    }

    public function not_repeat_slug($slug)
    {
        $search = $this->where('slug', '=', $slug)->count();
        if ($search)
            return $slug . '-01';
        else {
            return $slug;
        }
    }

    public function Environment()
    {
        return $this->hasMany('App\Environment', 'line_id');
    }

}

app/Http/Controllers/Admin/LineController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Environment;
use App\Http\Requests\LineRequest;
use App\Line;
use App\Product;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LineController extends Controller
{

    public function index()
    {
        $rows = Line::paginate(15);
        return view('admin.line.index', compact('rows'));
    }

    public function create()
    {
        session(['path' => Carbon::now()->timestamp]);
        return view('admin.line.create');
    }

    public function store(LineRequest $lineRequest, Line $line)
    {
        $lineRequest->merge(['slug' => str_slug($lineRequest->get('name')), 'descriptions' => json_encode($lineRequest->get('descriptions'))]);
        $new_line = $line->create($lineRequest->except(['environment']));
        if (!$new_line)
            return redirect()
                ->back()
                ->with('error', trans('returns.error_create', ['msg' => 'a Linha '. $lineRequest->get('name')]));

        if ($lineRequest->has('environments')) {
            $environment = new Environment();
            $environment->create_customized($lineRequest->get('environments'), $new_line->id);
        }

        if ($lineRequest->has('modules')) {
            $product = new Product();
            $product->create_customized(array_to_json($lineRequest->get('modules')));
        }

        return redirect()
            ->route('line.index')
            ->with('success', trans('returns.success_create', ['msg' => 'Linha '.$lineRequest->get('name'), 'url' => route('line.edit', $lineRequest->get('slug'))]));
    }

    public function edit($id)
    {
        $edit = Line::where('slug', '=', $id)->first();
        if (!$edit)
            return redirect()
                ->back()
                ->with('error', trans('returns.not_exist'));

        if ($edit->descriptions) {
            $edit->descriptions = json_decode($edit->descriptions, true);
        }


        return view('admin.line.edit', compact('edit'));
    }

    public function update($id, LineRequest $lineRequest)
    {
        $edit = Line::where('slug', '=', $id)->first();
        if (!$edit)
            return redirect()
                ->back()
                ->with('error', trans('returns.not_exist'));

        $lineRequest->merge(['slug' => str_slug($lineRequest->get('name')), 'descriptions' => json_encode($lineRequest->get('descriptions'))]);
        $edit->update($lineRequest->except(['environment']));

        $environment = new Environment();
        if ($lineRequest->has('environments')) {
            $environment->create_customized($lineRequest->get('environments'), $edit->id);
        }

        if ($lineRequest->has('itemsRemove')) {
            $environment->remove_env(explode(',',$lineRequest->get('itemsRemove')), $edit->id);
        }

        return redirect()
            ->route('line.index')
            ->with('success', trans('returns.success_update', ['msg' => 'Linha '.$lineRequest->get('name')]));
    }

    public function destroy($id)
    {
        $destroy = Line::where('slug', '=', $id);
        if (!$destroy->first())
            return redirect()
                ->back()
                ->with('error', trans('returns.not_exist'));

        $data = $destroy->first();

        if ($destroy->delete())
            return redirect()
                ->route('line.index')
                ->with('success', trans('returns.success_destroy', ['msg' => 'A Linha '. $data->name]));
        else {
            return redirect()
                ->route('line.index')
                ->with('error', trans('returns.error_destroy', ['msg' => 'a linha '. $data->name]));
        }
    }
    
}

resources/views/admin/line/create.blade.php
@extends('admin')

@section('sn')
    Nova Linha
@endsection

@section('b')
    <li>
        <a href="{!! route('line.index') !!}">
            Linhas
        </a>
    </li>
    <li class="active">
        Nova Linha
    </li>
@endsection

@section('act')
    <div class="col-lg-2 col-sm-4 col-xs-12">
        <a href="{!! route('line.index') !!}" class="btn btn-block btn-warning">
            <i class="fa fa-arrow-left"></i> Voltar
        </a>
    </div>
@endsection

@section('content')
    {!! Form::open(['route' => 'line.store', 'files' => true, 'class' => 'form-material form-horizontal']) !!}
    @include('admin.line.form')
    {!! Form::close() !!}
@endsection

resources/views/admin/line/edit.blade.php
@extends('admin')

@section('sn')
    Editar Linha
@endsection

@section('b')
    <li>
        <a href="{!! route('line.index') !!}">
            Linhas
        </a>
    </li>
    <li class="active">
        Nova Linha
    </li>
@endsection

@section('act')
    <div class="col-lg-2 col-sm-4 col-xs-12">
        <a href="{!! route('line.index') !!}" class="btn btn-block btn-warning">
            <i class="fa fa-arrow-left"></i> Voltar
        </a>
    </div>
    <div class="col-lg-2 col-sm-4 col-xs-12">
        <a href="{!! route('line.create') !!}" class="btn btn-block btn-success"
           title="Clique aqui para adicionar uma nova linha">
            <i class="fa fa-plus"></i> Adicionar Linha
        </a>
    </div>
@endsection

@section('content')
    {!! Form::model($edit, ['route' => ['line.update', $edit->slug], 'files' => true, 'method' => 'PATCH', 'class' => 'form-material form-horizontal']) !!}
    @include('admin.line.form')
    {!! Form::close() !!}
@endsection

resources/views/admin/line/environment.blade.php
<!-- environments -->
<div class="row" id="environment">
    <input type="hidden" name="env_itemsRemove" v-model="env.itemsRemove" />
    <ul class="nav nav-tabs list-inline">
        @foreach(setting('languages', true) as $key => $language)
            <li{!! $key == 0 ? ' class="active"' : '' !!}>
                <a href="#env-{!! $language->slug !!}" data-toggle="tab">
                    <span class="hidden-xs">{!! $language->name !!}</span>
                </a>
            </li>
        @endforeach
    </ul>
    <div class="tab-content">
        @foreach(setting('languages', true) as $key => $language)
            <div class="tab-pane fade{!! $key == 0 ? ' active in' : '' !!}" id="env-{!! $language->slug !!}">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="" class="col-md-12">
                            Título do Ambiente em {!! $language->name !!} <strong class="text text-danger">*</strong>
                        </label>
                        <div class="col-md-12">
                            {!! Form::text('', null, ['v-model' => 'env.name.'.$language->slug, 'class' => 'form-control', 'placeholder' => 'Nome no idioma '. $language->name]) !!}
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
    <div class="col-lg-6">
        <div class="form-group">
            <label class="col-md-12">
                Referência do Ambiente <strong class="text-danger">*</strong>
            </label>
            <div class="col-md-12">
                {!! Form::text('', null, ['v-model' => 'env.reference', 'class' => 'form-control', 'placeholder' => 'Digite aqui a referência']) !!}
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="form-group}">
            <label class="col-md-12">
                Cor do Ambiente <strong class="text-danger">*</strong>
            </label>
            <div class="col-md-12">
                {!! Form::select('', \App\Color::get()->pluck('select', 'id'), null, ['v-model' => 'env.color_id', 'id' => 'color', 'class' => 'form-control', 'placeholder' => 'Selecione a cor do ambiente']) !!}
            </div>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="form-group">
            <label class="col-md-12">
                Imagem do Ambiente <strong class="text-danger">*</strong>
            </label>
            <div class="col-md-12">
                <img v-if="env.upload.path" v-bind:src="env.upload.path + '/' + env.upload.w" width="50" />
                {!! Form::file('', ['v-on:change' => 'e_tmp_image($event)', 'id' => 'upload-clear', 'class' => 'form-control', 'placeholder' => 'Imagem']) !!}
                {!! Form::hidden('', null, ['v-model' => 'env.upload']) !!}
            </div>
        </div>
        <div class="form-group col-md-12">
            <button class="btn btn-success" v-on:click="e_save($event)" type="button">
                <i class="fa fa-plus"></i> @{{ env.wait == false ? 'Adicionar Ambiente' : 'Aguarde...' }}
            </button>
        </div>
    </div>
    <div class="col-md-12 table-responsive">
        <table class="table table-bordered">
            <thead>
            <tr>
                <td>Nome</td>
                <td>Cor</td>
                <td>Referência</td>
                <td>Imagem</td>
                <td>#</td>
            </tr>
            </thead>
            <tbody>
            @if (session()->has('environments'))
                @foreach(session()->get('environments') as $json)
                    @php
                        $env = json_decode($json);
                    @endphp
                    <tr id="{!! $env->id !!}">
                        <td>
                            @foreach($env->name as $name)
                                {!! $name !!}
                            @endforeach
                        </td>
                        <td v-html="e_show_color('{!! $env->color_id !!}')"></td>
                        <td>{!! $env->reference !!}</td>
                        <td>
                            @if ($env->upload)
                                <img src="{!! $env->upload->path . '/' . $env->upload->w !!}" width="50" />
                            @endif
                        </td>
                        <td>
                            {{--<button class="btn btn-success btn-xs" v-on:click="e_edit($event, '{!! $env->id !!}', true)" type="button">--}}
                                {{--<i class="fa fa-pencil"></i>--}}
                            {{--</button>--}}
                            <button class="btn btn-danger btn-xs" v-on:click="e_destroy($event, '{!! $env->id !!}', true)" type="button">
                                <i class="fa fa-trash"></i>
                            </button>
                            <input type="hidden" v-bind:value='e_toString({!! $json !!})' name="environments[]" />
                        </td>
                    </tr>
                @endforeach
            @endif
            @if (isset($edit) && $edit->Environment)
                @foreach($edit->Environment as $env)
                    @php
                        $json = [
                        'id' => $env->id,
                        'name' => $env->name_json,
                        'reference' => $env->reference,
                        'upload' => $env->upload_json,
                        'color_id' => $env->color_id
                        ];
                    @endphp
                    <tr id="{!! $env->id !!}">
                        <td>
                            @foreach($env->name_json as $name)
                                {!! $name !!}
                            @endforeach
                        </td>
                        <td v-html="e_show_color('{!! $env->color_id !!}')"></td>
                        <td>{!! $env->reference !!}</td>
                        <td>
                            @if ($env->upload)
                                @if (file_exists(public_path('/assets/environment/' . $env->upload_json->w)))
                                    <img src="{!! url('/assets/environment/' . $env->upload_json->w) !!}" width="50" />
                                @endif
                            @endif
                        </td>
                        <td>
                            {{--<button class="btn btn-success btn-xs" v-on:click="e_edit($event, '{!! $env->id !!}', true)" type="button">--}}
                                {{--<i class="fa fa-pencil"></i>--}}
                            {{--</button>--}}
                            <button class="btn btn-danger btn-xs" v-on:click="e_destroy($event, '{!! $env->id !!}', true)" type="button">
                                <i class="fa fa-trash"></i>
                            </button>
                            <input type="hidden" v-bind:value='e_toString({!! json_encode($json) !!})' name="environments[]" />
                        </td>
                    </tr>
                @endforeach
            @endif
            <tr v-for="(k, o) in env.rows" v-bind:id="o.id">
                <td>@{{ e_show_name(o.name) }}</td>
                <td>@{{ e_show_color(o.color_id) }}</td>
                <td>@{{ o.reference }}</td>
                <td>
                    <img v-bind:src="o.upload.path + '/' + o.upload.w" width="50" />
                </td>
                <td>
                    {{--<button class="btn btn-success btn-xs" v-on:click="e_edit($event, o.id)" type="button">--}}
                        {{--<i class="fa fa-pencil"></i>--}}
                    {{--</button>--}}
                    <button class="btn btn-danger btn-xs" v-on:click="e_destroy($event, o.id)" type="button">
                        <i class="fa fa-trash"></i>
                    </button>
                    <input type="hidden" v-bind:value="e_toString(o)" name="environments[]" />
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

resources/views/admin/line/form.blade.php
<div class="white-box" id="line">

    <div class="row">
        <h3 class="col-sm-12 bg-info text-white">Linha</h3>
    </div>

    <div class="row">
        <div class="col-lg-6">
            <div class="form-group{!! $errors->first('name') ? ' has-error' : '' !!}">
                <label for="" class="col-md-12">
                    Nome/Título da Linha <strong class="text-danger">*</strong>
                </label>
                <div class="col-md-12">
                    {!! Form::text('name', null, ['required', 'class' => 'form-control', 'placeholder' => 'Nome/Título da linha']) !!}
                    {!! $errors->first('name', '<span class="help-block">:message</span>') !!}
                </div>
            </div>
        </div>
    </div>
    <ul class="nav nav-tabs list-inline">
        @foreach(setting('languages', true) as $key => $language)
            <li{!! $key == 0 ? ' class="active"' : '' !!}>
                <a href="#{!! $language->slug !!}" data-toggle="tab">
                    <span class="hidden-xs">{!! $language->name !!}</span>
                </a>
            </li>
        @endforeach
    </ul>
    <div class="tab-content">
        @foreach(setting('languages', true) as $key => $language)
            <div class="tab-pane fade{!! $key == 0 ? ' active in' : '' !!}" id="{!! $language->slug !!}">
                {!! Form::textarea('descriptions['.$language->slug.']', null, ['class' => 'form-control', 'placeholder' => 'Descrição em '. $language->name]) !!}
            </div>
        @endforeach
    </div>

    <hr />

    <div class="row">
        <h3 class="col-sm-12 bg-info text-white">Ambientes</h3>
    </div>

    @include('admin.line.environment')

    <div class="row">
        <h3 class="col-sm-12 bg-info text-white">Módulos</h3>
    </div>

    @include('admin.line.modules')

</div>
<hr/>
<div class="col-lg-12">
    <div class="form-group">
        <button class="btn btn-primary" type="submit">
            <i class="fa fa-check"></i> Salvar
        </button>
    </div>
</div>
@section('js')
    {!! Html::script('/js/components/line-module-product.js') !!}
@endsection

resources/views/admin/line/index.blade.php
@extends('admin')

@section('sn')
    Linhas
@endsection

@section('b')
    <li class="active">
        Linhas
    </li>
@endsection

@section('act')
    <div class="col-lg-2 col-sm-4 col-xs-12">
        <a href="{!! route('line.create') !!}" class="btn btn-block btn-brown" title="Clique aqui para adicionar um novo curso">
            <i class="fa fa-plus"></i> Cadastrar Linha
        </a>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="white-box">
                {!! Form::open(['route' => ['line.index', old('name')], 'method' => 'GET']) !!}
                <div class="row">
                    <div class="form-group{!! $errors->first('name') ? ' has-error' : '' !!}">
                        <div class="col-lg-10">
                            {!! Form::text('name', request()->has('name') ? request('name') : null, ['class' => 'form-control', 'placeholder' => 'Procurar por nome']) !!}
                            {!! $errors->first('name', '<span class="help-block">:message</span>') !!}
                        </div>
                        <div class="col-lg-2">
                            <button type="submit" class="btn btn-block btn-primary">
                                <i class="fa fa-search"></i> Procurar
                            </button>
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
    <div class="row el-element-overlay">
        @if (isset($rows) && $rows->count())
            <div class="col-lg-12">
                <div class="white-box">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <td>Nome</td>
                            <td>Opções</td>
                            {{--<td>#Opções</td>--}}
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($rows as $row)
                            <tr>
                                <td>{!! $row->name !!}</td>
                                <td>
                                    <a href="{!! route('environment.create', ['line' => $row->id]) !!}" class="btn btn-brown" title="Clique aqui para adicionar um novo ambiente">
                                        Cadastrar Ambiente
                                    </a>
                                    <a class="btn btn-brown" href="{!! route('environment.index', ['line' => $row->id]) !!}">
                                        Gerenciar Ambientes
                                    </a>
                                </td>
                                {{--<td>--}}
                                    {{--<a href="{!! route('line.edit', $row->slug) !!}" class="btn btn-success btn-xs pull-left">--}}
                                        {{--<i class="fa fa-pencil"></i>--}}
                                    {{--</a>--}}
                                    {{--{!! Form::open(['route' => ['line.destroy', $row->slug], 'method' => 'DELETE', 'class' => 'pull-left delete']) !!}--}}
                                    {{--<button class="btn btn-danger btn-xs" type="submit">--}}
                                        {{--<i class="fa fa-trash"></i>--}}
                                    {{--</button>--}}
                                    {{--{!! Form::close() !!}--}}
                                {{--</td>--}}
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        @endif
    </div>
    @if (isset($rows))
        <div class="row">
            <div class="col-lg-12">
                @include('admin.elements.pagination', ['paginator' => $rows])
            </div>
        </div>
    @endif
@endsection

@section('js')
    {!! Html::script('/js/components/delete.js') !!}
@endsection