routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
if (isset($router)) {

    $router->get('auth', 'Auth\LoginController@login')->name('login');
    $router->post('auth', 'Auth\LoginController@login')->name('auth');
    $router->get('logout', 'Auth\LoginController@logout')->name('logout');

    $router->get('/', 'Site\HomeController@index')->name('front.index');
    $router->get('linha/{slug}', 'Site\HomeController@show_line')->name('linha.show');
    $router->get('contato', 'Site\ContactController@index')->name('contact.index');
    $router->post('contato', 'Site\ContactController@store')->name('contact.store');
    $router->get('a-empresa', 'Site\HomeController@about')->name('about.index');
    $router->get('video-institucional', 'Site\HomeController@video')->name('video.index');

    $router->group(['middleware' => 'auth', 'prefix' => 'admin'], function () use ($router) {
        $router->get('/', function () {
            return redirect()->route('line.index');
        });
        $router->get('/panel', function () {
            return redirect()->route('line.index');
        })->name('dashboard');

        $router->resource('user', 'Admin\UserController');

        //Multi Móveis
        $router->resource('line', 'Admin\LineController');
        $router->resource('lead', 'Admin\LeadController', [
            'except' => ['create', 'edit', 'destroy']
        ]);

        $router->resource('product', 'Admin\ProductController');
        $router->resource('blog', 'Admin\BlogController');

        $router->resource('environment', 'Admin\EnvironmentController');
    });

}

app/Grid.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\File;
use Illuminate\Support\MessageBag;

class Grid extends Model
{

    use SoftDeletes;

    protected $fillable = [
        'product_id', 'color_id',
        'reference', 'upload'
    ];

    public function getNameJsonAttribute()
    {
        return json_decode($this->name);
    }

    public function getUploadJsonAttribute()
    {
        return json_decode($this->upload);
    }

    public function save_grids(array $grids, $product_id)
    {
        if (count($grids)) {
            $error = new MessageBag();
            foreach ($grids as $grid) {

                $save = json_decode($grid, true);

                $this->upload($save['upload']);

                $save['upload']['path'] = url('/assets/environment/');
                $save['upload'] = json_encode($save['upload']);
                $save['product_id'] = $product_id;
                $find = $this->where('id', '=', $save['id'])->first();
                unset($save['id']);
                if (!$find) {
                    if (!$this->create($save)) {
                        $error->add($save['reference'], 'Falha ao criar variação do módulo');
                    }
                } else {
                    if (!$this->update($save)) {
                        $error->add($save['reference'], 'Falha ao atualizar a variação do módulo');
                    }
                }
            }
            return $error;
        }
    }

    private function upload($upload)
    {
        if (File::exists(public_path('/uploads/tmp-image/' . $upload['name']))) {
            if (!File::isDirectory(public_path('/assets/product/')))
                File::makeDirectory(public_path('/assets/product/'), 0775, true);

            File::move(public_path('/uploads/tmp-image/' . $upload['name']), public_path('/assets/product/' . $upload['name']));
            File::delete(public_path('/uploads/tmp-image/' . $upload['name']));
        }

        if (File::exists(public_path('/uploads/tmp-image/' . $upload['w']))) {
            if (!File::isDirectory(public_path('/assets/product/')))
                File::makeDirectory(public_path('/assets/product/'), 0775, true);

            File::move(public_path('/uploads/tmp-image/' . $upload['w']), public_path('/assets/product/' . $upload['w']));
            File::delete(public_path('/uploads/tmp-image/' . $upload['w']));
        }
    }

    public function remove_env($array, $id)
    {
        foreach ($array as $item) {
            $exist = $this->where('id', '=', $item)
                ->where('product_id', '=', $id);
            if ($exist->count()) {
                $exist->delete();
            }
        }
    }

}

app/Line.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Line extends Model
{

    use SoftDeletes;

    protected $fillable = [
        'name', 'slug', 'descriptions'
    ];

    public function getDescriptionsJsonAttribute()
    {
        return json_decode($this->descriptions, true);
    }

    public function not_repeat_slug($slug)
    {
        $search = $this->where('slug', '=', $slug)->count();
        if ($search)
            return $slug . '-01';
        else {
            return $slug;
        }
    }

    public function Environment()
    {
        return $this->hasMany('App\Environment', 'line_id');
    }

}

app/Http/Controllers/Site/ContactController.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Requests\ContactRequest;
use App\Lead;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;

class ContactController extends Controller
{

    public function index()
    {
        return view('site.contact');
    }

    public function store(ContactRequest $contactRequest, Lead $lead)
    {
        $contactRequest->merge(['type' => 'contato']);
        if ($lead->create($contactRequest->all())) {

            Mail::send('emails.contact', ['body' => $contactRequest->all()], function($m) {
                $m->from('no-reply@multimoveis.com.br', 'Contato Site');
                $m->to(setting('contact'), 'Contato')->subject('Contato realizado pelo site');
            });

            return redirect()->route('contact.index')
                ->with('success', 'Obrigado, entraremos em contato com vocês em breve.');
        }
        return redirect()->back()
            ->with('error', 'Ops, não foi possível enviar o formulário, tente novamente.');
    }

}

app/Http/Controllers/Site/HomeController.php
<?php

namespace App\Http\Controllers\Site;

use App\Line;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{

    public function index(Line $line)
    {
        $lines = $line->all();
        return view('site.index', compact('lines'));
    }

    public function about()
    {
        return view('site.about');
    }

    public function video()
    {
        return view('site.video');
    }

    public function show_line($slug, Line $line)
    {
        $show = $line->whereSlug($slug)->first();
        if (!$show)
            return redirect('/')->with('error', 'Linha não encontrada.');

        return view('site.show_line', compact('show'));
    }

}

resources/views/site/about.blade.php
@extends('front-interna')

@section('content')
    <style>
        h2, label {
            color: #FFF;
        }
        p {
            color: #FFF;
        }
    </style>
    <main class="container">
        @include('site.elements.header-front')
        <section class="home">
            <div class="container2">
                <h2>Quem Somos</h2>
                <p class="p1">
                    A Multimóveis, fundada em 1995, na Serra Gaúcha, está localizada no maior pólo moveleiro
                    do Brasil. Com a missão de oferecer bem estar em mobiliário, de forma criativa, flexível
                    e rentável, em harmonia com o ser humano, a sociedade e o meio ambiente, a empresa produz
                    móveis de qualidade e com design arrojado respeitando as diferentes culturas mundiais e
                    aos exigentes consumidores deste mundo moderno.
                </p>

                <p class="p3">
                    Utilizando tecnologia de ponta, os produtos da Multimóveis Baby, Multimóveis Decor, Multipla
                    e Eko Ambientes se diferenciam através do acabamento superior, demonstrando o cuidado e
                    carinho na fabricação dos móveis. Nosso desafio é ser referência em mobiliário para o bem
                    estar das pessoas, oferecendo aos clientes soluções práticas e facilidades, com foco nos
                    mais altos padrões em serviços, qualidade e acabamentos disponíveis no mercado. Para a
                    Multimóveis, o cliente é a prioridade das suas ações, e a equipe seu maior patrimônio.
                    De bem com a vida, mais do que um slogan: uma filosofia de trabalho e de vida.
                </p>
                <h2>Histórico</h2>

                <p class="p3">
                    Fundada em 01 de janeiro de 1995, fruto da união dos objetivos comuns, sonhos e muito
                    trabalho de seus sócios diretores Ivo Cusin, Euclides Longhi e Maristela Cusin Longhi,
                    a Multimóveis Indústria de Móveis, localizada em Bento Gonçalves, Rio Grande do Sul,
                    iniciou suas atividades fabricando móveis infantis e em pouco tempo tornou-se uma
                    das maiores fábricas especializadas no segmento.
                </p>

                <p class="p3">
                    Como estratégia de expansão e visando uma maior atuação no mercado nacional e internacional,
                    em 1998 é adquirida a Decormóvel Indústria de Móveis, fabricante de racks, estantes,
                    escrivaninhas e dormitórios. Após quatro anos ela foi  incorporada à Multimóveis, dando
                    origem a nova identidade visual da empresa. Em 2009, buscando ampliar seu nicho de mercado,
                    a Multimóveis lançou a EKO Ambientes, desenvolvida para buscar um espaço diferenciado no
                    mercado de móveis planejados. Já em 2011 surge a Multipla, marca de móveis modulados
                    lançada para atender um público que busca uma casa bem decorada, com design moderdo aliado
                    a preços acessíveis. Com as novas propostas de produtos que surgiram ao longo dos anos, em
                    2012 a Multimóveis modernizou sua logomarca, deixando-a mais dinâmica e corporativa para
                    que pudesse abranger as demais marcas que surgiram na empresa.
                </p>

                <p class="p3">
                    Atualmente, com uma área construída de 22.500m², a Multimóveis conta com 280 funcionários
                    e alia equipamentos de última geração à capacitação profissional de sua equipe. Além do
                    mercado brasileiro, os produtos são aceitos mundialmente, sendo exportados para mais de 40 países.
                </p>


                <h2>NEGÓCIO</h2>

                <p class="p3">Bem estar em mobiliário.</p>


                <h2>MISSÃO</h2>
                <p class="p3">
                    Oferecer bem estar em mobiliário, de forma flexível, criativa e rentável, em harmonia
                    com o ser humano, a sociedade e o meio ambiente.
                </p>

                <h2>PRINCÍPIOS</h2>
                <p class="p3">
                    Cliente: nossa prioridade.
                    <br>Responsabilidade: envolvimento e comprometimento de todos.
                    <br>Equipe: o grande diferencial.
                    <br>Rentabilidade: garantia de continuidade e crescimento.
                </p>

                <h2>VISÃO</h2>
                <p class="p3">Ser referência em mobiliário para o bem estar das pessoas.</p>
            </div>
        </section>
    </main>
    <div class="clearfix"></div>

    @include('site.elements.footer-show')

@endsection

resources/views/site/contact.blade.php
@extends('front-interna')

@section('content')
    <style>
        h3, label {
            color: #FFF;
        }
    </style>
    <main class="container">
        @include('site.elements.header-front')
        <section class="home">
            <h3>Fale conosco</h3>
            {!! Form::open(['route' => 'contact.store']) !!}
            <div class="form-group">
                <label for="name">
                    Nome <strong class="text-danger">*</strong>
                </label>
                {!! Form::text('name', null, ['class' => 'form-control', 'required', 'placeholder' => 'Nome *']) !!}
            </div>
            <div class="form-group">
                <label for="email">
                    E-mail <strong class="text-danger">*</strong>
                </label>
                {!! Form::text('email', null, ['class' => 'form-control', 'required', 'placeholder' => 'E-mail *']) !!}
            </div>
            <div class="form-group">
                <label for="phone">
                    Telefone <strong class="text-danger">*</strong>
                </label>
                {!! Form::text('phone', null, ['class' => 'form-control', 'required', 'placeholder' => 'Telefone *']) !!}
            </div>
            <div class="form-group">
                <label for="message">
                    Mensagem <strong class="text-danger">*</strong>
                </label>
                {!! Form::textarea('message', null, ['class' => 'form-control', 'required', 'placeholder' => 'Digite aqui a mensagem *']) !!}
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">
                    Enviar contato
                </button>
            </div>
            {!! Form::close() !!}
        </section>
    </main>
    <div class="clearfix"></div>

    @include('site.elements.footer-show')

@endsection

resources/views/site/index.blade.php
@extends('front')

@section('content')

    <main class="container">
        @include('site.elements.header-front')
        <section class="home">
            @foreach($lines as $line)
                @php
                    $environment = $line->Environment->first();
                @endphp
                <div class="row">
                    <a href="{!! route('linha.show', $line->slug) !!}" class="col-xs-12 item baby">
                        <figure class="fundo">
                            <img src="{!! url('/assets/environment/'. $environment->upload_json->home) !!}" width="437" height="218" alt="Multimóveis Baby">
                        </figure>
                        <div class="white-box">
                            <figure>
                                {!! str_limit($line->descriptions_json['portugues'], 150) !!}
                            </figure>
                        </div>
                    </a>
                </div>
            @endforeach
        </section>
        <div class="clearfix"></div>
        <section class="bottom">
            <address>
                MULTIMÓVEIS<br />
                Rua Carlos Dreher Neto, 1918 - Caixa Postal 639<br />
                Bento Gonçalves - RS - Brasil<br />
                CEP 95706-44<br />
                54 2102 4000 - <a href="mailto:multimoveis@multimoveis.com">multimoveis@multimoveis.com</a>
            </address>
        </section>
    </main>

@endsection

resources/views/site/show_line.blade.php
@extends('front-interna')

@section('content')
    @php
        $environment = $show->Environment->first();
    @endphp


    <main class="internas baby">
        {{--<figure class="logo-interna">--}}
            {{--<img src="{!! url('/assets/images/multimoveis-baby-logo-interna.png') !!}" alt="">--}}
        {{--</figure>--}}
        <ul class="list-inline pull-right">
            <li><a href="#"><img src="{!! url('/assets/images/icons/blog-internas.png') !!}" alt=""></a></li>
            <li><a href="#"><img src="{!! url('/assets/images/icons/facebook-internas.png') !!}" alt=""></a></li>
            <li><a href="#"><img src="{!! url('/assets/images/icons/instagram-internas.png') !!}" alt=""></a></li>
            <li>
                <form class="" action="" method="post">
                    <input type="text" name="search_interna" id="search_interna" value="" placeholder="BUSCA" required>
                </form>
            </li>
        </ul>
        <div class="row">
            <div class="col-xs-12">
                <div id="carousel-internas" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        @foreach($show->Environment as $key => $env)
                        <li data-target="#carousel-internas" data-slide-to="{!! $key !!}" class="active"></li>
                        @endforeach
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        @foreach($show->Environment as $key => $env)
                        <div class="item{!! $key == 0 ? ' active' : '' !!}">
                            <img src="{!! url('/assets/environment/'. $env->upload_json->interna) !!}" alt="{!! $env->name_json->portugues !!}">
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
        @include('site.elements.nav-bar')
        <div class="content">
            <div class="content-options" style="background-color: #30BFA9;">
                <a href="#">
                    <figure class="lupa" style="background-color: #30BFA9;">
                        <img src="{!! url('/assets/images/icons/lupa.png') !!}" alt="Lupa">
                    </figure>
                </a>
                <a href="#">
                    <figure class="modulos">
                        <img src="{!! url('/assets/images/icons/opcoes.png') !!}" alt="">
                    </figure>
                </a>
                <a href="#">
                    <figure class="modulos">
                        <img src="{!! url('/assets/images/icons/opcoes-2.png') !!}" alt="">
                    </figure>
                </a>
            </div>
            <div class="owl-carousel owl-theme" id="owl-carousel">
                @foreach($show->Environment as $env)
                    <a href="javascript:void(0)" class="item">
                        <figure>
                            <img src="{!! url('/assets/environment/'. $env->upload_json->home) !!}" alt="">
                            <figcaption>
                                {!! $env->name_json->portugues !!}
                            </figcaption>
                        </figure>
                    </a>
                @endforeach
            </div>
        </div>
    </main>
    <div class="clearfix"></div>

    @include('site.elements.footer-show')

    <div class="fd_overlay"></div>
    <div class="fd_modal">
        <a href="#" class="close-modal"><img src="{!! url('/assets/images/icons/close-modal.png') !!}" alt=""></a>
        <div id="carousel-modal" class="carousel slide" data-ride="carousel">
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                @foreach($show->Environment as $key => $env)
                    <div class="item{!! $key == 0 ? ' active' : '' !!}">
                        <img src="{!! url('/assets/environment/'. $env->upload_json->home) !!}" alt=""  data-zoom-image="/assets/images/slider/slider-1_zoom.jpg">
                    </div>
                 @endforeach
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-modal" role="button" data-slide="prev">
                <img src="{!! url('/assets/images/icons/arrow-left.png') !!}" alt="<<">
            </a>
            <a class="right carousel-control" href="#carousel-modal" role="button" data-slide="next">
                <img src="{!! url('/assets/images/icons/arrow-right.png') !!}" alt=">>">
            </a>
        </div>
    </div>


@endsection

resources/views/site/video.blade.php
@extends('front-interna')

@section('content')
    <style>
        h2, label {
            color: #FFF;
        }
        p {
            color: #FFF;
        }
    </style>
    <main class="container">
        @include('site.elements.header-front')
        <section class="home">
            <h2>Vídeo Institucional</h2>
            <p>
                Confira abaixo um pouco mais sobre nossa empresa.
            </p>

            <iframe width="500" height="480" src="https://www.youtube.com/embed/dfYRGu0L-z0" frameborder="0" allowfullscreen></iframe>
        </section>
    </main>
    <div class="clearfix"></div>

    @include('site.elements.footer-show')

@endsection